HEADER/urls.py
from django.urls import path
from .import views
app_name="HEADER"
urlpatterns=[
    path('hlogin',views.hlogin,name='hlogin'),
    path('ahome',views.ahome,name='ahome'),
    path('haction/<str:category>',views.haction,name='haction'),
    path('hlanguage/<str:language>',views.hlanguage,name='hlanguage'),
    path('up',views.up,name='up'),
    path('theater',views.theater,name='theater'),
    path('carter/<int:m_id>',views.carter,name='carter'),
    path('seats/<int:sid>/<int:timeid>',views.seats,name='seats'),
    path('booking/<int:table_id>',views.booking,name='booking'),
    path('payment/<int:bookid>',views.payment,name='payment'),
    path('c_psw',views.c_psw,name='c_psw'),

]

USER/urls.py
from django.urls import path
from .import views

app_name='USER'
urlpatterns=[
    path('ulogin',views.ulogin,name='ulogin'),
    path('usignup',views.usignup,name='usignup'),
    path('email_exit',views.email_exit,name='email_exit'),
    path('ahome',views.ahome,name='ahome'),
    path('getaction/<str:category>',views.getaction,name='getaction'),
    path('getlanguage/<str:language>',views.getlanguage,name='getlanguage'),
    path('up',views.up,name='up'),
    path('theater',views.theater,name='theater'),
    path('carter/<int:m_id>',views.carter,name='carter'),
    path('user_seats/<int:sid>/<int:timeid>',views.user_seats,name='user_seats'),
    path('u_booking/<int:table_id>',views.u_booking,name='u_booking'),
    path('cw_psw',views.cw_psw,name='cw_psw'),
    path('payment/<int:bookid>',views.payment,name='payment'),
    # path('seats/<int:sid>/<int:tid>',views.seats,name='seats'),
    # path('booking/<int:table_id>',views.booking,name='booking'),

]

showtime/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('HEADER/',include('HEADER.urls')),
    path('USER/',include('USER.urls')),
    path('towner/',include('towner.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

USER/models.py
from django.db import models

class Userdetails(models.Model):
    uname = models.CharField(max_length = 20)
    username = models.CharField(max_length = 20)
    uemail = models.CharField(max_length = 20)
    uphone = models.BigIntegerField()
    password = models.CharField(max_length=30)
    udob = models.CharField(max_length = 20)
    ugender = models.CharField(max_length = 20)
    
    class Meta:
        db_table = 'user_user'

# Create your models here.

USER/views.py
from django.shortcuts import render,redirect
from USER.models import Userdetails
from django.core.mail import send_mail
from USER.decorators import auth_user
from towner.models import Moviedetails,BookingDetails,Theater_screen,time_table,SeatsName,Tdetails,BookingDetails
from django.http import JsonResponse

# Create your views here.
def ulogin(request):
    if request.method == 'POST':
        username = request.POST['uname']
        password = request.POST['psw'] 


        try:
            ulogin = Userdetails.objects.get(username=username,password=password)
            request.session['u_id'] = ulogin.id
            
            return redirect("USER:ahome")
        except:
            msg = "invalid username or password"
            print('niiuwdhiu ')
            return render(request,"ulogin.html",{"error_message":msg})
    return render (request,'ulogin.html')

def usignup(request):
    if request.method== 'POST':
 
        name = request.POST['fullname'] # inputname 
        username = request.POST['username']
        email = request.POST['email']
        phnumber = request.POST['phnumber']
        password = request.POST['password']
        birthday = request.POST['dob']
        gender = request.POST['gender']

        email_exist = Userdetails.objects.filter(uemail = email).exists()
        if not email_exist:
            
            obj =Userdetails(uname = name,
                         username = username,
                         uemail = email,
                         uphone = phnumber,
                         password = password,
                         udob = birthday,
                         ugender = gender,
                    
                    )
            obj.save()
    return render (request,'usignup.html')

def email_exit(request):
    uemail=request.POST['email']
    email_exit = Userdetails.objects.filter( uemail = uemail).exists()
    return JsonResponse({'status':email_exit})

@auth_user
def ahome(request):
    details=Moviedetails.objects.all()
    user= Userdetails.objects.get(id=request.session['u_id'])
    return render (request,'user_home.html',{'uname':user.uname,'det':details,})

def getaction(request,category):
    details=Moviedetails.objects.filter(general=category)
    # language=Moviedetails.objects.filter(language=lan)
    user= Userdetails.objects.get(id=request.session['u_id'])
    return render (request,'user_home.html',{'uname':user.uname,'det':details,})

def getlanguage(request,language):
    details=Moviedetails.objects.filter(language=language)
    # language=Moviedetails.objects.filter(language=lan)
    user= Userdetails.objects.get(id=request.session['u_id'])
    return render (request,'user_home.html',{'uname':user.uname,'det':details,})    
@auth_user
def up(request):
    user= Userdetails.objects.get(id=request.session['u_id'])
    return render (request,'user_upcoming.html',{'user':user})
@auth_user
def theater(request):
    user= Userdetails.objects.get(id=request.session['u_id'])
    time_table1=time_table.objects.all()
    return render (request,'u_theater.html',{'user':user,'table':time_table1})

# def booking(request,m_id):
#     time_table1= time_table.objects.filter(movie_id=table_id)    
#     user= Userdetails.objects.get(id=request.session['u_id'])
#     moviedatail = Moviedetails.objects.get(id=table_id)
#     print(moviedatail.movie_name)
#     return render (request,'user_booking.html',{'user':user,'movie':moviedatail,'table':time_table1,'theater':towner})
@auth_user
def u_booking(request,table_id):
    time_table1= time_table.objects.filter(movie_id=table_id)
    user= Userdetails.objects.get(id=request.session['u_id'])   
    towner= Tdetails.objects.all()
    moviedetail = Moviedetails.objects.get(id=table_id)
    print(moviedetail.movie_name)
    return render (request,'user_booking.html',{'movie':moviedetail,'user':user,'table':time_table1,'theater':towner})

@auth_user
def carter(request,m_id):
    details=Moviedetails.objects.get(id=m_id)
    user= Userdetails.objects.get(id=request.session['u_id'])
    return render (request,'u_carter.html',{'user':user,'movie':details})

@auth_user
def user_seats(request, sid,timeid):
    bookingdetails=BookingDetails.objects.filter(timetable_id=timeid)
    seat_name=[]
    s_name1=""
    for booking in bookingdetails:
        s_name1 += booking.seats       
       
    s_name2=s_name1[:len(s_name1)-1]

  
    seatsdetails=SeatsName.objects.all()
    Time_table= time_table.objects.all()
    user= Userdetails.objects.get(id=request.session['u_id'])


    seatsObj = Theater_screen.objects.get(id=sid)
    
    ss=int(seatsObj.seats)
    print(seatsObj.seats)


    if request.method== 'POST'  :   
        noofseats = request.POST['count']
        amount = request.POST['price']
        seats = request.POST['seat']
        
        

        timetable=time_table.objects.get(id=timeid)
        # price=int(amount)
        # print(type(price))
        # mid=int(price)
        # print(type(price))
        # obb=BookingDetails.objects.get(id=mid)
        # print(obb)
        obj = BookingDetails(
                         noofseats = noofseats,
                         rupes = amount,
                         seats = seats,
                         timetable_id = timetable.id,

                    )
        obj.save()
        return redirect('USER:payment',obj.id)


    return render (request,'user_seats.html',{'seatsObj':seatsObj,'user':user,'seatno':ss,'seatt':seatsdetails,'Time_table':Time_table,'book':bookingdetails,'booked_seat':s_name2})


def cw_psw(request):
    user= Userdetails.objects.get(id=request.session['u_id'])
    msg = ""
    if request.method == 'POST':
        user_oldpsw = request.POST['oldpsw']
        user_newpsw = request.POST['newpsw']
        user_confirmpwd = request.POST['confirmpsw']

        user = Userdetails.objects.get(id =request.session['u_id'])
        # teacher.password = '007'
        # teacher.save()
        if user.password == user_oldpsw:
            if user_newpsw == user_confirmpwd:
                user.password = user_newpsw
                user.save()
                msg = "password changed"
            else:
                msg = "password doesnot match"
        else:
            msg ="incorrect password"
    return render (request,'user_chpsw.html',{'status':msg ,'user':user})

def logout(request):
    del request.session['u_id']
    request.session.flush()
    return redirect('USER:ulogin')

@auth_user
def payment(request,bookid):
    user= Userdetails.objects.get(id=request.session['u_id'])
    bookingdetails=BookingDetails.objects.get(id=bookid)

    # userid=request.session['u_id']
    # products_orderdata =BookingDetails.objects.filter(user=userid, status='added_to bag')
    # amount = request.POST['price']
    # order_currency = 'INR'
    # order_recepit = 'order_rcptid_11'
    # notes = {'Shipping address' : 'Bommanahali,Banglore'}
    # type(amount)
    # client = razorpay.Client(auth=('rzp_test_jznmHCFBf6ZMUd','hMGwzen13b1QwDmJxDtyAUNy'))
    # payment = client.order.create{{"amount":amount,"currency":order_currency,"receipt":order_receipt,'notes':notes}}
    # return JsonResponse(payment)

    return render (request,'user_payment.html',{'user':user,'book':bookingdetails,})

USER/templates/movie_details.html
{% extends 'user_base.html' %}
{% block title%}
theaters
{% endblock%}

{% block name %}{{user.username}}{% endblock %}


{% block content %}
<div class="container">
    <table>
        <tr>
            <td colspan="15" colspan="4">
                    <div class="col">
                        <div class="card h-100">
                            <img src="/static/images/on/cart.jpg" class="card-img-top" alt="..." style="height:1500px ;">
                            <div class="card-body">
                                <h5 class="card-title">Carter</h5>
                                <p class="card-text">Carter is a 2022 South Korean action thriller film directed by Jung
                                    Byung-gil.The film stars Joo Won, Lee Sung-jae, Jeong So-ri and Kim Bo-min.
                                    <h5 class="card-title">Plot</h5>
                                    In the midst of a deadly pandemic caused by a virus which makes the infected patients 
                                    violent and zombie-like, originating from the DMZ that has already devastated the 
                                    United States and North Korea, a man wakes up in a blood-soaked bed in a motel room 
                                    in Seoul, with a cross-shaped scar on the back of his head. Armed CIA agents burst 
                                    in and threaten him demanding the whereabouts of Dr. Jung Byung-ho. With no 
                                    recollections of his past, he doesn't know who he is or why he is there, let 
                                    alone who Dr. Jung is. A female voice inside his ear which only he can hear, 
                                    tells him that his name is Carter and he needs to accept her directions if he 
                                    wants to live. Following her instructions, he escapes the room and enters a 
                                    public bath where nearly a hundred gangsters attack and try to kill him. 
                                    Thanks to his lethal fighting skills, he survives their assault.
                                </p>
                                <h5 class="card-title">Theater: Magic Frames Radha</h5>
                             
                            </div>
                            <div class="card-footer">
                                <small class="text-muted" ><a href="{% url 'USER:booking' %}"><center>Book Now</center></a></small>
                            </div>
                        </div>
                    </div>
                
            </td>
        </tr>
    </table>
</div>
<style></style>
{% endblock %}

USER/templates/u_carter.html
{% extends 'user_base.html' %}
{% block title%}
theaters
{% endblock%}

{% block name %}{{user.username}}{% endblock %}


{% block content %}
<div class="container">
    <table>
        <tr>
            <td colspan="15" colspan="4">
                    <div class="col">
                        <div class="card h-100">
                            <img src="{{movie.picture.url}}" class="card-img-top" alt="..." style="height:1500px ;">
                            <div class="card-body">
                                <h5 class="card-title">{{movie.movie_name}}</h5>
                                    <h5 class="card-title">Plot</h5>
                                    {{movie.details}}
                                </p>
                                <h5 class="card-title">Theater:{{movie.theater.tname}}</h5>                             
                            </div>
                            <div class="card-footer">
                                <small class="text-muted" ><a href="{% url 'USER:u_booking' movie.id %}"><center>Book Now</center></a></small>
                            </div>
                        </div>
                    </div>                
            </td>  
        </tr>
    </table>
</div>
{% endblock %}

USER/templates/u_theater.html
{% extends 'user_base.html' %}
{% block title%}
theaters
{% endblock%}

{% block name %}{{user.username}}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="theater">TODAY'S MOVIES IN KOZHIKODE THEATRES</h1>
    <hr class="hr1"><br>
    <table  class="booking" style="width:100%;">
        <tr>

            <th>t_id</th>
            <th>tname</th>
            <th>movie</th>
            <th>time_one</th>
            <th>time_two</th>
            <th>time_three</th>
            <th>book_now</th>
            
        </tr>
        {% for time in table %}
        <tr>

            <td>{{forloop.counter}}</td>
            <td>{{time.theater.tname}}</td>
            <td>{{time.movie.movie_name}}</td>
            <td>{{time.time_one}}</td>
            <td>{{time.time_two}}</td>
            <td>{{time.time_three}}</td>
            <td><button><a href="{% url 'USER:carter' time.movie.id %}">Book</a></button></td>
        </tr>
        {% endfor %}
      </table>
</div>

{% endblock %}

USER/templates/user_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

	<link rel="stylesheet" href="{% static 'css/afooter.css' %}">
	<link rel="stylesheet" href="{% static 'css/aside-nav.css' %}">

	<style>
		@media only screen and (max-width: 700px) {
	/* .sidebar {
     visibility: hidden;
	 } */

    

}


	</style>


</head>

<body>
	<div class="mainbody">
		<div class="wrapper d-flex">
			<div class="sidebar">
				<ul>
					<li><a href="{% url 'USER:ahome' %}"><i class="fas fa-home"></i>Home</a></li>
					<li><a href="{% url 'USER:theater' %}"></i>Theater</a></li>
					<li class="nav-item dropdown notification1">
						<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Language
						</a>
						<ul class="dropdown-menu">
							<li><a style="background:none;" class="dropdown-item" href="{% url 'USER:getlanguage' 'malayalam' %}">Malayalam</a></li>
							<li><a style="background:none;" class="dropdown-item" href="{% url 'USER:getlanguage' 'tamil' %}">Tamil</a></li>
							<li><a style="background:none;" class="dropdown-item" href="{% url 'USER:getlanguage' 'hindi' %}">Hindi</a></li>
							<li><a style="background:none;" class="dropdown-item" href="{% url 'USER:getlanguage' 'english' %}">English</a></li>
						</ul>
					</li>
					<li class="notification2"><a href="{% url 'USER:up' %}">Coming soon</a><span class="number2"></span></li>
					</li>
					<li class="coming_ho"><a href="#"><img src="/static/images/up/avatar.jpg" class="coming_img"
								alt="..."></a>
						<div class="middle">
							<a href="{% url 'USER:up' %}"><p class="text">View more</p></a>
						</div>
					</li>
					<!-- <li><a href="#"><i class="fas fa-signal"></i>Reports</a></li> -->
				</ul>
				<!-- <p class="myproject px-3">PROJECTS</p>
				<ul>
					<li><a href="#">Website redesign</a></li>
					<li><a href="#">GraphQL API</a></li>
					<li><a href="#">Customer migration guides</a></li>
					<li><a href="#">Profit sharing program</a></li>
				</ul> -->
				<div class="userProfile">

					<div class="dropdown">
						<a type="text" class= "dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
							aria-expanded="false">
							<i class="far fa-user-circle xyz"></i> <p style="padding-left:5px; display:inline-block">{{uname |title}}</p>
						</a>

						<ul class="dropdown-menu">
							<li><a class="dropdown-item" style="background:none;" href="{% url 'USER:cw_psw' %}">Change Password</a></li>
							<li><a class="dropdown-item"  style="background:none;" href="{% url 'USER:ulogin' %}">Logout</a></li>
							<!-- <li><a class="dropdown-item" style="background:none;"  href="#">Something else here</a></li> -->
						</ul>
					</div>
				</div>

			</div>


			<div class="navi">
				<nav class="navbar navbar-expand-lg ">
					<div class="container-fluid">
						<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
							data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02"
							aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
							<ul class="navbar-nav me-auto ms-auto mb-2 mb-lg-0">
								<img src="/static/images/s1.jpg" class="showtime" alt="...">

								<li class="nav-item">
									<a class="nav-link active" aria-current="page" href="{% url 'USER:ahome' %}">All</a>
								</li>
								<li class="nav-item">
									<a class="nav-link active" aria-current="page" href="{% url 'USER:getaction' 'action' %}">Action</a>
								</li> 
								<li class="nav-item">
									<a class="nav-link active" aria-current="page" href="{% url 'USER:getaction' 'comedy' %}">Comedy</a>
								</li>
								<li class="nav-item">
									<a class="nav-link active" aria-current="page" href="{% url 'USER:getaction' 'mystery' %}">Mystery</a>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</div>
		</div>

		<div class="films">
			<div class="row row-cols-1 row-cols-md-3 g-4">
				{% for movie in det %}
				<div class="col">
					<div class="card h-100">
						<img src="{{movie.picture.url}}" class="card-img-top" alt="...">
						<div class="card-body">
							<h5 class="card-title">{{movie.movie_name}}</h5>
							<p class="card-text">{{movie.details}}</p>
						</div>
						<div class="card-footer">
							<small class="text-muted"><a href="{% url 'USER:carter' movie.id %}">Book Now</a></small>
						</div>
					</div>
				</div>
				{% endfor %}
				
			</div>
		</div>

		<footer class="kilimanjaro_area">
			<!-- Top Footer Area Start -->
			<div class="foo_top_header_one section_padding_100_70">
				<div class="container">
					<div class="row">
						<div class="col-12 col-md-3">
						
						</div>

						<div class="col-12 col-md-3">
							<div class="kilimanjaro_part">
								<h5>About Us</h5>
								<p>Here Tickets re-imagines the most convenient way for users to plan a night out at the movies.
								   The  website provide relevant informations, trailers and synopses to help moviegoers 
								   make the best decision on what to see.</p>
							</div>
							<div class="kilimanjaro_part ">
								<h5>Social Links</h5>
								<ul class="kilimanjaro_social_links">
									<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i> Facebook</a></li>
									<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i> Twitter</a></li>
									<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i> Pinterest</a>
									</li>
									<li><a href="#"><i class="fa fa-youtube" aria-hidden="true"></i> YouTube</a></li>
									<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i> Linkedin</a></li>
								</ul>
							</div>
						</div>

				
						<div class="col-12 col-md-3">
							<div class="kilimanjaro_part">
								<h5>Upcoming movies</h5>
								<div class="kilimanjaro_blog_area">
									<div class="kilimanjaro_thumb">
										<img class="img-fluid" src="/static/images/up/adipurush.jpg"alt="">
								</div>
									<a href="#">Adipurush</a>
									<p class="kilimanjaro_date">Relese date 21 Jan 2023</p>
								</div>
								<div class="kilimanjaro_blog_area">
									<div class="kilimanjaro_thumb">
										<img class="img-fluid" src="/static/images/up/avatar.jpg"alt="">
									</div>
									<a href="#">Avatar</a>
									<p class="kilimanjaro_date">Relese date 21 Jan 2023</p>
								</div>
								<div class="kilimanjaro_blog_area">
									<div class="kilimanjaro_thumb">
										<img class="img-fluid" src="/static/images/up/puss.jpg"alt="">

									</div>
									<a href="#">Puss in Boots: The Last Wish </a>
									<p class="kilimanjaro_date">Relese date 21 Jan 2023</p>
								</div>
							</div>
						</div>
						<div class="col-12 col-md-3">
							<div class="kilimanjaro_part">
								<h5>Quick Contact</h5>
								<div class="kilimanjaro_single_contact_info">
									<h5>Phone:</h5>
									<p>+255 255 54 53 52 <br> +255 255 53 52 51</p>
								</div>
								<div class="kilimanjaro_single_contact_info">
									<h5>Email:</h5>
									<p>support@email.com <br> company@email.com</p>
								</div>
							</div>
							<div class="kilimanjaro_part">
								<h5><a href="#">Ongling movies</a></h5>
								<!-- <div class="kilimanjaro_works">
									<a class="kilimanjaro_works_img" href="img/gallery/1.jpg"><img
											src="img/gallery/1.jpg" alt=""></a>
									<a class="kilimanjaro_works_img" href="img/gallery/4.jpg"><img
											src="img/gallery/4.jpg" alt=""></a>
									<a class="kilimanjaro_works_img" href="img/gallery/5.jpg"><img
											src="img/gallery/5.jpg" alt=""></a>
									<a class="kilimanjaro_works_img" href="img/gallery/7.jpg"><img
											src="img/gallery/7.jpg" alt=""></a>
									<a class="kilimanjaro_works_img" href="img/gallery/10.jpg"><img
											src="img/gallery/10.jpg" alt=""></a>
									<a class="kilimanjaro_works_img" href="img/gallery/11.jpg"><img
											src="img/gallery/11.jpg" alt=""></a> -->
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Footer Bottom Area Start -->
			<div class=" kilimanjaro_bottom_header_one section_padding_50 text-center">
				<div class="container">
					<div class="row">
						<div class="col-12">
							<p>© All Rights Reserved by <a href="#">My Footer<i class="fa fa-love"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</footer>

	</div>
<style>
		.coming_img {
			width: 200px;
			height: 230px;
			opacity: 1;
			display: block;
			transition: .5s ease;
			backface-visibility: hidden;

		}

		.coming_ho:hover .coming_img {
			opacity: 0.3;
		}

		.coming_ho:hover .middle {
			opacity: 1;
		}

		.middle {
			transition: .5s ease;
			opacity: 0;
			position: absolute;
			top: 55%;
			left: 50%;
			transform: translate(-50%, -50%);
			-ms-transform: translate(-50%, -50%);
			text-align: center;
			
		}

		.text {
			color: white;
			font-size: 20px;
			font-family: Ink Free;
			/* padding: 12px 22px; */
		}

		.text-muted a {
			font-family: fantasy;
			font-size: 20px;
			text-decoration: none;
			color: rgb(221, 245, 8);

		}

		.text-muted a:hover {
			background-color: rgb(5, 5, 5);
		}

		.showtime {
			width: 400px;
			height: 80px;
			margin-left: -110px;
		}

		.card-footer {
			background-color: rgb(186, 93, 93);
		}

		.card-footer:hover {
			background-color: rgb(0, 0, 0);
		}

		.navi {
			margin-left: 16%;
			width: 90%;
			position: relative;
		}

		.navi .navbar .navbar-nav .nav-item {
			padding-left: 25px;
			padding-right: 25px;
			margin-top: 25px;
		}

		.navi .navbar .navbar-nav .nav-item .nav-link {
			font-size: 20px;
			color: black;
			font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
		}

		.navi .navbar-nav {
			height: 70px;
		}

		.navi .navbar .navbar-nav .nav-link {
			box-shadow: inset 0 0 0 0 #54b3d6;
			color: #54b3d6;
			margin: 0 -.25rem;
			padding: 0 .25rem;
			transition: color .3s ease-in-out, box-shadow .3s ease-in-out;
		}

		.navi .navbar .navbar-nav .nav-link:hover {
			box-shadow: inset 100px 0 0 0 #54b3d6;
			color: white;
		}




		.films {
			width: 70%;
			margin-left: 22%;
			margin-top: 40px;
		}

		.sidebar .nav-item .dropdown-menu {
			margin-left: -15px;

		}

		.footer-clean {
			padding: 50px 0;
			background-color: #fff;
			color: #4b4c4d;
		}

		.footer-clean h3 {
			margin-top: 0;
			margin-bottom: 12px;
			font-weight: bold;
			font-size: 16px;
		}

		.footer-clean ul {
			padding: 0;
			list-style: none;
			line-height: 1.6;
			font-size: 14px;
			margin-bottom: 0;
		}

		.footer-clean ul a {
			color: inherit;
			text-decoration: none;
			opacity: 0.8;
		}

		.footer-clean ul a:hover {
			opacity: 1;
		}

		.footer-clean .item.social {
			text-align: right;
		}

		@media (max-width:767px) {
			.footer-clean .item {
				text-align: center;
				padding-bottom: 20px;
			}
		}

		@media (max-width: 768px) {
			.footer-clean .item.social {
				text-align: center;
			}
		}

		.footer-clean .item.social>a {
			font-size: 24px;
			width: 40px;
			height: 40px;
			line-height: 40px;
			display: inline-block;
			text-align: center;
			border-radius: 50%;
			border: 1px solid #ccc;
			margin-left: 10px;
			margin-top: 22px;
			color: inherit;
			opacity: 0.75;
		}

		.footer-clean .item.social>a:hover {
			opacity: 0.9;
		}

		@media (max-width:991px) {
			.footer-clean .item.social>a {
				margin-top: 40px;
			}
		}

		@media (max-width:767px) {
			.footer-clean .item.social>a {
				margin-top: 10px;
			}
		}

		.footer-clean .copyright {
			margin-top: 14px;
			margin-bottom: 0;
			font-size: 13px;
			opacity: 0.6;
		}
	</style>


	<script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>