HEADER/urls.py
from django.urls import path
from .import views
app_name="HEADER"
urlpatterns=[
    path('hlogin',views.hlogin,name='hlogin'),
    path('ahome',views.ahome,name='ahome'),
    path('haction/<str:category>',views.haction,name='haction'),
    path('hlanguage/<str:language>',views.hlanguage,name='hlanguage'),
    path('up',views.up,name='up'),
    path('theater',views.theater,name='theater'),
    path('carter/<int:m_id>',views.carter,name='carter'),
    path('seats/<int:sid>/<int:timeid>',views.seats,name='seats'),
    path('booking/<int:table_id>',views.booking,name='booking'),
    path('payment/<int:bookid>',views.payment,name='payment'),
    path('c_psw',views.c_psw,name='c_psw'),

]

USER/urls.py
from django.urls import path
from .import views

app_name='USER'
urlpatterns=[
    path('ulogin',views.ulogin,name='ulogin'),
    path('usignup',views.usignup,name='usignup'),
    path('email_exit',views.email_exit,name='email_exit'),
    path('ahome',views.ahome,name='ahome'),
    path('getaction/<str:category>',views.getaction,name='getaction'),
    path('getlanguage/<str:language>',views.getlanguage,name='getlanguage'),
    path('up',views.up,name='up'),
    path('theater',views.theater,name='theater'),
    path('carter/<int:m_id>',views.carter,name='carter'),
    path('user_seats/<int:sid>/<int:timeid>',views.user_seats,name='user_seats'),
    path('u_booking/<int:table_id>',views.u_booking,name='u_booking'),
    path('cw_psw',views.cw_psw,name='cw_psw'),
    path('payment/<int:bookid>',views.payment,name='payment'),
    # path('seats/<int:sid>/<int:tid>',views.seats,name='seats'),
    # path('booking/<int:table_id>',views.booking,name='booking'),

]

showtime/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('HEADER/',include('HEADER.urls')),
    path('USER/',include('USER.urls')),
    path('towner/',include('towner.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

towner/urls.py
from django.urls import path
from .import views

app_name='towner'
urlpatterns=[
    path('clogin',views.clogin,name='clogin'),
    path('csignup',views.csignup,name='csignup'),
    path('eg',views.eg,name='eg'),
    path('addmovies',views.addmovies,name='addmovies'),
    path('towner_home',views.towner_home,name='towner_home'),
    path('cw_psw',views.cw_psw,name='cw_psw'),
    path('de_movies',views.de_movies,name='de_movies'),
    path('delm/<int:mid>',views.del_movie,name='delmovies'),
    path('editm/<int:mid>',views.edit_movies,name='editmovie'),
    path('img_edit/<int:mid>',views.img_edit,name='img_edit'),
    path('ahome',views.ahome,name='ahome'),
    path('carter/<int:m_id>',views.carter,name='carter'),
    path('up',views.up,name='up'),
    path('seats/<int:sid>/<int:tid>',views.seats,name='seats'),
    path('booking/<int:table_id>',views.booking,name='booking'),
    path('screen',views.screen,name='screen'),
    path('seats_name',views.seats_name,name='seats_name'),
    path('time_table',views.Time_table,name='time_table'),
    path('action',views.action,name='action'),
    path('seatsrefrence/<int:sid>',views.seatsrefrence,name='seatsrefrence'),

]

towner/models.py
from django.db import models


# Create your models here.
class Tdetails(models.Model):
    cname = models.CharField(max_length = 20)
    tname = models.CharField(max_length = 20)
    tscreen = models.CharField(max_length = 20)
    taddress = models.CharField(max_length = 20)
    # tprice = models.CharField(max_length = 20)
    tuname = models.CharField(max_length=30)
    temail = models.CharField(max_length = 20)
    tphone = models.BigIntegerField()
    tpassword = models.CharField(max_length=30) 
    tgender = models.CharField(max_length = 20)


class Moviedetails(models.Model):
    movie_name = models.CharField(max_length = 20)
    release_date = models.CharField(max_length = 20)
    movie_screen = models.CharField(max_length = 20)
    # time_am = models.CharField(max_length = 20)
    # time_pm = models.CharField(max_length = 20)
    # price = models.CharField(max_length = 20)
    details = models.CharField(max_length = 20)
    general = models.CharField(max_length= 20, default= '')
    language = models.CharField(max_length= 20, default= '')
    picture = models.ImageField(upload_to = 'movie/' )
    theater = models.ForeignKey(Tdetails,on_delete=models.CASCADE, default= '')


class Theater_screen(models.Model):
    screen_name = models.CharField(max_length = 20)
    seats = models.BigIntegerField()
    theater = models.ForeignKey(Tdetails,on_delete=models.CASCADE, default= '')


class Theater_seats(models.Model):
    screen_id = models.ForeignKey(Theater_screen,on_delete=models.CASCADE)

class Date(models.Model):
    name=models.CharField(max_length = 20)
    datees=models.CharField(max_length = 20)   


class time_table(models.Model):
    date = models.ForeignKey(Date,on_delete=models.CASCADE)
    time_one= models.CharField(max_length = 20)
    time_two= models.CharField(max_length = 20)
    time_three= models.CharField(max_length = 20)
    # gender = models.CharField(max_length = 20, default= '')
    # language = models.CharField(max_length = 20, default= '')
    theater = models.ForeignKey(Tdetails,on_delete=models.CASCADE)
    screen = models.ForeignKey(Theater_screen,on_delete=models.CASCADE)
    movie = models.ForeignKey(Moviedetails,on_delete=models.CASCADE)

class Towner_seats(models.Model):
    screen = models.ForeignKey(Theater_screen,on_delete=models.CASCADE)
    seats = models.CharField(max_length = 20, default= '')
    status = models.CharField(max_length = 20, default= 'Vacant')
 
class SeatsName(models.Model):
    screen = models.ForeignKey(Theater_screen,on_delete=models.CASCADE)
    seats = models.CharField(max_length = 20, default= '')
    status = models.CharField(max_length = 20, default= 'Vacant')
    theater = models.ForeignKey(Tdetails,on_delete=models.CASCADE)


class SeatsName(models.Model):
    screen = models.ForeignKey(Theater_screen,on_delete=models.CASCADE)
    seats = models.CharField(max_length = 20, default= '')
    status = models.CharField(max_length = 20, default= 'Vacant')
    theater = models.ForeignKey(Tdetails,on_delete=models.CASCADE)

class Seatdetails(models.Model):
    screen = models.ForeignKey(Theater_screen,on_delete=models.CASCADE)
    seats = models.CharField(max_length = 20, default= '')
    status = models.CharField(max_length = 20, default= 'Vacant')
    theater = models.ForeignKey(Tdetails,on_delete=models.CASCADE)    



class SeatInfo(models.Model):
    seat = models.ForeignKey(Seatdetails,on_delete=models.CASCADE,default= '')
    noofseats = models.CharField(max_length = 20)
    rupes = models.CharField(max_length = 20)
    timetable = models.ForeignKey(time_table,on_delete=models.CASCADE)
    customer = models.ForeignKey(Tdetails,on_delete=models.CASCADE, default= '')

class Booking(models.Model):
    seat = models.ForeignKey(Seatdetails,on_delete=models.CASCADE,default= '')
    noofseats = models.CharField(max_length = 20)
    amount = models.CharField(max_length = 20)
    timetable = models.ForeignKey(time_table,on_delete=models.CASCADE)
    customer = models.ForeignKey(Tdetails,on_delete=models.CASCADE, default= '')

class BookingDetails(models.Model):
    noofseats = models.CharField(max_length = 20)
    rupes = models.CharField(max_length = 20)
    seats = models.CharField(max_length = 20, default='')
    timetable = models.ForeignKey(time_table,on_delete=models.CASCADE)
    status = models.CharField(max_length = 20, default='Pending')

towner/views.py
from django.shortcuts import render,redirect
from towner.models import Tdetails,Moviedetails,Theater_screen,SeatsName,time_table,Date,Seatdetails,BookingDetails
from django.http import JsonResponse
from datetime import datetime, timedelta


# Create your views here.

def clogin(request):
    if request.method == 'POST':
        tuname = request.POST['username']
        tpassword = request.POST['password'] 

        try:
            clogin = Tdetails.objects.get(tuname=tuname,tpassword=tpassword)
            request.session['c_id'] = clogin.id
            
            return redirect("towner:towner_home")
        except:
            msg = "invalid username or password"
            print('niiuwdhiu ')
            return render(request,"clogin.html",{"error_message":msg})
    return render (request,'clogin.html')

def csignup(request):
    if request.method== 'POST':

        cname = request.POST['townername']
        tname = request.POST['tname']
        tscreen = request.POST['tscreen']
        tad = request.POST['add']
        # tprice = request.POST['tprice']
        tuname = request.POST['tusername']
        temail = request.POST['temail']
        tphone =  request.POST['tnumber']
        tpassword = request.POST['tpassword']
        tgender = request.POST['tgender']
        obj =Tdetails(cname = cname,
                        tname = tname,
                        tscreen = tscreen,
                        taddress = tad,
                        # tprice = tprice,
                        tuname = tuname,
                        temail = temail,
                        tphone = tphone,
                        tpassword = tpassword,
                        tgender = tgender,                   
                    )
        obj.save()
    return render (request,'csignup.html')



def addmovies(request):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    if request.method== 'POST':

        movie_name = request.POST['m_name'] # inputname 
        r_date = request.POST['r_date']
        screen = request.POST['screen']
        # time_am = request.POST['time_am']
        # time_pm = request.POST['time_pm']
        general = request.POST['gender']
        language = request.POST['language']
        # price = request.POST['price']
        details = request.POST['add']
        image = request.FILES['pic']
        t_id =request.session['c_id']
        obj =Moviedetails(movie_name = movie_name,
                         release_date = r_date,
                         movie_screen = screen,
                        #  time_am = time_am,
                        #  time_pm = time_pm,
                         general = general,
                         language = language,
                        #  price = price,
                         details = details,
                         picture = image,
                         theater_id =t_id,
                    )
        obj.save()
        msg = "Movie added succesfuly"
    else:
        msg=""
    return render (request,'add_movies.html',{'customer':towner,'status':msg})



def eg(request):
    return render (request,'eg.html')

def towner_home(request):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    return render (request,'towner_home.html',{'customer':towner})


def cw_psw(request):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    msg = ""
    if request.method == 'POST':
        toldpsw = request.POST['oldpsw']
        tnewpsw = request.POST['newpsw']
        tconfirmpwd = request.POST['confirmpsw']

        towner = Tdetails.objects.get(id =request.session['c_id'])
        if towner.tpassword == toldpsw:
            if tnewpsw == tconfirmpwd:
                towner.tpassword = tnewpsw
                towner.save()
                msg = "password changed"
            else:
                msg = "password doesnot match"
        else:
            msg ="incorrect password"
    return render (request,'towner_chpsw.html',{'status':msg,'customer':towner})


def de_movies(request):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    movie = Moviedetails.objects.all()
    print(movie)
    return render (request,'delete_movies.html',{'movie_details':movie,'customer':towner})

def del_movie(request,mid):
    movie = Moviedetails.objects.get(id = mid)
    movies = Moviedetails.objects.all()
    movie.delete()
    msg='movie deletyed succesfully'
    return render (request,'delete_movies.html',{'movie_details':movies,'status':msg })

def edit_movies(request,mid):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    movie = Moviedetails.objects.get(id=mid)
    msg=''
    if request.method=='POST':
        movie.movie_name = request.POST['m_name']
        movie.release_date = request.POST['r_date']
        movie.movie_screen = request.POST['screen']
        # movie.time_am = request.POST['time_am']
        # movie.time_pm = request.POST['time_pm']
        movie.general = request.POST['gender']
        movie.language = request.POST['language']
        # movie.price = request.POST['price']
        movie.details = request.POST['add']
        # movie.picture = request.FILES['pic']
        movie.save()
        msg='movie edited succesfully'

    return render (request,'towner_edit.html',{'movie_details':movie,'status':msg,'customer':towner})

def img_edit(request,mid):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    movie = Moviedetails.objects.get(id=mid)
    msg=''
    if request.method=='POST':
        movie.picture = request.FILES['pic']
        movie.save()
        msg='movie edited succesfully'

    return render (request,'image_edit.html',{'movie_details':movie,'status':msg,'customer':towner})

def logout(request):
    del request.session['c_id']
    request.session.flush()
    return redirect('towner:clogin')

def ahome(request):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    details=Moviedetails.objects.all()

    Time_table=time_table.objects.all()
    presentday = datetime.now()
    tomorrow = presentday + timedelta(1)
    dayafter = presentday + timedelta(2)
    Todaysdate=presentday.strftime('%d-%m-%Y')
    Tomorrowsdate=tomorrow.strftime('%d-%m-%Y')
    Dayafterdate=dayafter.strftime('%d-%m-%Y')

    Today=Date.objects.get(id=1)
    Today.datees=Todaysdate
    Today.save()

    Tmrw=Date.objects.get(id=2)
    Tmrw.datees=Tomorrowsdate
    Tmrw.save()

    Dayft=Date.objects.get(id=3)
    Dayft.datees=Dayafterdate
    Dayft.save()
  
    return render (request,'movie_home.html',{'det':details,'customer':towner.tuname,'gender':Time_table})
    
def carter(request,m_id):
    details=Moviedetails.objects.get(id=m_id)
    towner= Tdetails.objects.get(id=request.session['c_id'])
    return render (request,'towner_carter.html',{'customer':towner,'movie':details})

def up(request):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    return render (request,'towner_upcoming.html',{'customer':towner})


def seats(request, sid,tid):
    towner= Tdetails.objects.get(id=tid)
    seatsdetails=Seatdetails.objects.filter(screen_id=sid,theater_id=tid)
    print(seatsdetails)
    seatsObj = Theater_screen.objects.get(theater_id=tid,id=sid)
    
    ss=int(seatsObj.seats)
    print(seatsObj.seats)
    
    # bookdetails=SeatInfo.objects.all()

    return render (request,'towner_seats.html',{'customer':towner, 'seatsObj':seatsObj,'seatno':ss,'seatt':seatsdetails })

def booking(request,table_id):
    time_table1= time_table.objects.filter(movie_id=table_id)  
      
    towner= Tdetails.objects.get(id=request.session['c_id'])
    moviedetail = Moviedetails.objects.get(id=table_id)
    print(moviedetail.movie_name)
    return render (request,'towner_booking.html',{'movie':moviedetail,'table':time_table1,'customer':towner})


def screen(request):
    towner= Tdetails.objects.get(id=request.session['c_id'])
    if request.method== 'POST':
        screen = request.POST['screen'] # inputname 
        seats = request.POST['seats']
        t_id =request.session['c_id']

        obj =Theater_screen(screen_name = screen,
                         seats = seats,
                         theater_id =t_id,
                        
                    )
        obj.save()
    return render (request,'towner_screen.html',{'customer':towner})

def seats_name(request):
    details=Theater_screen.objects.all()

    towner= Tdetails.objects.get(id=request.session['c_id'])
    if request.method== 'POST'  :   
        screens = request.POST['screen_name']
        seats = request.POST['seats']
        status='vacant'
    

        scid=int(screens)
        print(scid)
        theaterdetails=Tdetails.objects.get(id=request.session['c_id'])
        obb=Theater_screen.objects.get(id=scid)
        print(obb.id)
        
        obj =Seatdetails(
                         seats = seats,
                         screen_id = obb.id,
                         status=status,
                         theater_id=theaterdetails.id  
                    )
        obj.save()
    return render (request,'towner_seatsname.html',{'customer':towner,'det':details})


def Time_table(request):

    movie= Moviedetails.objects.all()
    details=Theater_screen.objects.all()   
    towner= Tdetails.objects.get(id=request.session['c_id'])
    Dat=Date.objects.all()
    if request.method== 'POST':
        dates = request.POST['date'] # inputname 
        time_one = request.POST['time_one']
        time_two = request.POST['time_two']
        time_three = request.POST['time_three']
        # gender = request.POST['gender']
        # language = request.POST['language']
        t_id =request.session['c_id']
        screens = request.POST['screen_name']
        movies = request.POST['mmid']
        scid=int(screens)
        print(type(scid))
        mid=int(movies)
        oid=int(dates)
        omp=Date.objects.get(id=oid)
        print(type(scid))
        obp=Moviedetails.objects.get(id=mid)

towner/templates/clogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Login Page in HTML with CSS Code Example</title>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">


	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
		integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="./style.css">
	<link rel="stylesheet" href="{% static 'css/clogin.css' %}">
	<!-- <script src="{% static 'js/jquery.js' %}"></script> -->

</head>

<body>
	<!-- partial:index.partial.html -->

	<div class="box-form">
		<div class="left">
			<div class="overlay">
				<h1>SHOW <span style="margin-left: 50px;">TIME</span> </h1><br>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
					Curabitur et est sed felis aliquet sollicitudin</p>
				<span>
					<p>Login with social media</p>
					<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
					<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i> Login with Twitter</a>
				</span>
			</div>
		</div>


		<div class="right">
			<h5>Login</h5>
			<form action="" method="POST">
				{% csrf_token %}
				<p>Don't have an account? <a href="{% url 'towner:csignup' %}">Creat Your Account</a> it takes less than a minute</p>
				<div class="inputs">
					<input type="text" placeholder="user name" name="username">
					<br>
					<input type="password" placeholder="password" name="password">
				</div>

				<br><br>

				<div class="remember-me--forget-password">
					<!-- Angular -->
					<label>
						<input type="checkbox" name="item" checked />
						<span class="text-checkbox">Remember me</span>
					</label>
					<p>forget password?</p>
				</div>

				<br>
				<button>Login</button>
			</form>
			{{error_message}}
		</div>

	</div>
	<!-- partial -->
</body>

</html>

towner/templates/delete_movies.html
{% extends 'towner_base.html' %}
{% block title%}
theaters
{% endblock%}
{% block name %}{{customer.tuname}}{% endblock %}

{% block content %}

{% if movie_details %}
    <table style="width:100%">
        <tr>
            <th>id_no</th>
            <th>Movie Name</th>
            <th>Release Date</th>
            <th>Screen</th>
            <!-- <th>Showtime-AM</th>
            <th>Showtime-PM</th> -->
            <th>Price</th>
            <th>Details</th>
            <th>Images</th>
            <th>General</th>
            <th>Language</th>
            <th>Delete</th>
            <th>Edit</th>
            <th>Image edit</th>
            {% comment %} 
            
            {% endcomment %}
            
            
        </tr>
        {% for student in movie_details %}
       
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{student.movie_name}}</td>
            <td>{{student.release_date}}</td>
            <td>{{student.movie_screen}}</td>
            <!-- <td>{{student.time_am}}</td> -->
            <!-- <td>{{student.time_pm}}</td> -->
            <td>{{student.price}}</td>
            <td>{{student.details}}</td>
            <td><img src="{{student.picture.url}}" alt="" width="100%" height="150px"></td>
            <td>{{student.general}}</td>
            <td>{{student.language}}</td>
            <td><a href="{% url 'towner:delmovies' student.id %}">Delete</a></td>
            <td><a href="{% url 'towner:editmovie' student.id %}">Edit</a></td>
            <td><a href="{% url 'towner:img_edit' student.id %}">Image Edit</a></td>
            {% comment %}
            {% endcomment %}

        </tr>
        {% endfor %}
    </table>
    <span>{{status}}</span>
    {% else %}
    <h1>no data</h1>
    {% endif %}

    <style>
        table, th, td {
                        border: 1px solid black;
                        /* border-collapse: collapse; */
                        /* height: 150px; */

                      }
    </style>

{{error_message}}
{% endblock %}

towner/templates/eg.html
<!DOCTYPE html>
<html lang="en" xmlns = "http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

   
</head>
<body onload = "changeImage()">

    <img id="img" src="/static/images/up/avatar.jpg">
</body>


<html 























    
</body>
</html>

towner/templates/movie_explanation.html
{% extends 'towner_base.html' %}
{% block title%}
theaters
{% endblock%}

{% block name %}{{customer.tuname}}{% endblock %}


{% block content %}
<div class="container">
    <table>
        <tr>
            <td colspan="15" colspan="4">
                    <div class="col">
                        <div class="card h-100">
                            <img src="/static/images/on/cart.jpg" class="card-img-top" alt="..." style="height:1500px ;">
                            <div class="card-body">
                                <h5 class="card-title">Carter</h5>
                                <p class="card-text">Carter is a 2022 South Korean action thriller film directed by Jung
                                    Byung-gil.The film stars Joo Won, Lee Sung-jae, Jeong So-ri and Kim Bo-min.
                                    <h5 class="card-title">Plot</h5>
                                    In the midst of a deadly pandemic caused by a virus which makes the infected patients 
                                    violent and zombie-like, originating from the DMZ that has already devastated the 
                                    United States and North Korea, a man wakes up in a blood-soaked bed in a motel room 
                                    in Seoul, with a cross-shaped scar on the back of his head. Armed CIA agents burst 
                                    in and threaten him demanding the whereabouts of Dr. Jung Byung-ho. With no 
                                    recollections of his past, he doesn't know who he is or why he is there, let 
                                    alone who Dr. Jung is. A female voice inside his ear which only he can hear, 
                                    tells him that his name is Carter and he needs to accept her directions if he 
                                    wants to live. Following her instructions, he escapes the room and enters a 
                                    public bath where nearly a hundred gangsters attack and try to kill him. 
                                    Thanks to his lethal fighting skills, he survives their assault.
                                </p>
                                <h5 class="card-title">Theater: Magic Frames Radha</h5>
                             
                            </div>
                            <div class="card-footer">
                                <small class="text-muted" ><a href="{% url 'USER:booking' %}"><center>Book Now</center></a></small>
                            </div>
                        </div>
                    </div>
                
            </td>
        </tr>
    </table>
</div>
<style></style>
{% endblock %}

towner/templates/t_action.html
{% extends 'user_base.html' %}
{% block title %}
theaters
{% endblock%}

{% block name %}{{customer.tuname}}{% endblock %}

{% block content %}





{% endblock %}

towner/templates/towner_carter.html
{% extends 'towner_base.html' %}
{% block title%}
theaters
{% endblock%}

{% block name %}{{customer.tuname}}{% endblock %}

{% block content %}
<div class="container">
    <table>
        <tr>
            <td colspan="15" colspan="4">
                    <div class="col">
                        <div class="card h-100">
                            <img src="{{movie.picture.url}}" class="card-img-top" alt="..." style="height:1500px ;">
                            <div class="card-body">
                                <h5 class="card-title">{{movie.movie_name}}</h5>
                                    <h5 class="card-title">Plot</h5>
                                    {{movie.details}}
                                
                                <h5 class="card-title">Theater:{{movie.theater.tname}}</h5>                             
                            </div>
                            <div class="card-footer">
                                <small class="text-muted" ><a href="{% url 'towner:booking' movie.id  %}"><center>Book Now</center></a></small>
                            </div>
                        </div>
                    </div>                
            </td>  
        </tr>
    </table>
</div>
<style></style>
{% endblock %}

towner/templates/towner_chpsw.html
{% extends 'towner_base.html' %}
{% block title%}
theaters
{% endblock%}
{% block name %}{{customer.tuname}}{% endblock %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <label for="oldpassword">old Password:</label>
    <input type="password" id="oldpwd" name="oldpsw"><br><br>

    <label for="newPassword">New Password:</label>
    <input type="password" id="newPwd" name="newpsw"><br><br>

    <label for="confirmPassword">Confirm Password:</label>
    <input type="password" id="confirmpwd" name="confirmpsw"><br><br>

    <button type="submit">change password</button>
    {{status}}
</form>

{% endblock %}

towner/templates/towner_home.html
{% extends 'towner_base.html' %}
{% block title%}
theaters
{% endblock%}
{% block name %}{{customer.tuname}}{% endblock %}

{% block content %}

<div class="container">

    <div class="row">
  
      <div class="col-sm">
  
            <button><a href="{% url 'towner:addmovies' %}">Add Movies</a></button>  
      </div>
  
      <div class="col-sm">
  
        <button><a href="{% url 'towner:time_table' %}">Add details</a></button>  
      </div>
  
      <div class="col-sm">
  
            <button class="text-muted"><a href="{% url 'towner:de_movies' %}">Delete/Edit Movies</a></button>  
      </div>
  
    </div>
  
  

  <div class="row">
  
    <div class="col-sm">

          <button><a href="{% url 'towner:screen' %}">Add Screen</a></button>  
    </div>

   


    <!-- <div class="col-sm">

      <button><a href="{% url 'towner:seats_name' %}">Add Seatname</a></button>  
    </div> -->

  </div>
</div>

<style>
    .row{
            margin-top: 100px;
            margin-bottom: 100px;
    }
    button{
        width: 200px;
        height: 100px;
        color: rgb(233, 254, 10);
		font-size: 20px;
        background-color: rgb(186, 93, 93);
        border: rgb(186, 93, 93);;
    }
		button a {
			font-family: fantasy;
			font-size: 20px;
			text-decoration: none;
			color: rgb(221, 245, 8);

		}

		button a:hover {
			background-color: rgb(5, 5, 5);
            color: rgb(233, 254, 10);
            text-decoration: none;

		}
</style>
{% endblock %}